### ISSUE TITLE
Create a Design System and apply it to the current UI

### ISSUE THREAD

**Issue by dabeeeenster** [SolidStateGroup/bullet-train-api#2113]
**Describe the solution you'd like**

Incrementally rollout the new design system for app.flagsmith.com.

## Stage 0 - Setup

- [x] Upgrade Bootstrap, setup bootstrap variables with the aim on removing custom css for components (e.g. button-primary) https://github.com/Flagsmith/flagsmith/pull/2289

## Stage 1 - Components 

Implement components, utilising bootstrap utils (ms-5 col-md etc text-<color> bg-<color>) etc and deleting bespoke css.

If a component has a variant, implement a theme property (See Button.tsx) that allows defining variants as properties.

All components should be tested in both light and dark mode and in Safari/Chrome.

- [x] Create button component with all variants
- [x] Typography (size, family, weight and line heights)
- [x] Text input / area
- [x] Switch
- [x] Dark mode switcher
- [x] Checkbox
- [x] Modals (generic, not styling every individual modal's content)
- [x] Info
- [x] Error message
- [x] Select
- [x] Tags
- [x] Chips (e.g. invite users)
- [x] Tabs (full width) + Pills - combine these to 1 component with a theme "tab" | "pill"
- [x] Radio
- [x] CodeHelp
- [x] Date select
- [x] Side Modals - this will require matching styles of the segment and feature modals
- [x] Panels and list items
Double Check https://github.com/Flagsmith/flagsmith/issues/2463 to make sure it is resolved
- [x] Side nav + navbar / combine projects page with org dropdown
- [x] Identity / Segment override icons
- [x] Panel pagination

## Stage 2 - Page / Organism development 

Implement grid based layouts according to the column view in Figma, these should be responsive and use standard column, padding and margin utils. Avoid bespoke styles, delete any current bespoke styles that we are replacing, avoid adhoc pixel values. 

**Add pages (e.g. login, features) as you go, modals e.g. schedule updates, create/edit feature.**

- [x] Account tabs
- [x] Features List
- [x] Create First Organisation  
- [x] Project Settings
- [x] Compare
- [x] Segments List
- [x] Create / Edit  Segment 
- [x] Login / Signup
- [x] Segment overrides
- [x] Create First Project
- [x] Project list
- [x] Edit Feature
- [x] Feature-Specific segments 
- [x] Feature Settings
- [x] Audit Log
- [x] Integrations
- [x] Scheduling 
- [x] Create environment 
- [x] Change Request list
- [x] Change Request detail 
- [x] Identities
- [x] Identity  
- [x] Environment Settings   
- [x] Organisation settings 
- [x] Dark mode run-through

**Comment by kyle-ssg** [comment]
Duplicate of https://github.com/Flagsmith/flagsmith/issues/2328, closed and moved description here.
