### ISSUE TITLE
Epic: Change requests for segments

### ISSUE THREAD

**Issue by matthewelwell** [SolidStateGroup/bullet-train-api#4044]
### Is your feature request related to a problem? Please describe.

When editing segments, I want to be able to request a review from other members of my organisation. 

### Describe the solution you'd like.

Extend the Change Requests functionality to be able to operate on segments as well as features. 

### Describe alternatives you've considered

N/a

**Comment by kyle-ssg** [comment]
Feedback from what we found

- [x] Remove environments from change requests at the project level
- [x] The Order of change requests seemingly random - should be date descending
- [x] In order to Store original rule ids so we can compare and diff change requests appropriately, as discussed let's call this field version_of to rules so we have a reference to the original rule that was potentially changed 
- [x] Approve is throwing a 500
```
    - curl 'https://api-staging.flagsmith.com/api/v1/projects/8500/change-requests/483/approve/' \
    -   -H 'accept: */*' \
    -   -H 'accept-language: en-GB,en;q=0.9' \
    -   -H 'authorization: Token e163db1b90f7d08f024800558c134464ed6ef2c2' \
    -   -H 'content-type: application/json' \
    -   -H 'origin: http://localhost:8080' \
    -   -H 'priority: u=1, i' \
    -   -H 'referer: http://localhost:8080/' \
    -   -H 'sec-ch-ua: "Google Chrome";v="131", "Chromium";v="131", "Not_A Brand";v="24"' \
    -   -H 'sec-ch-ua-mobile: ?0' \
    -   -H 'sec-ch-ua-platform: "macOS"' \
    -   -H 'sec-fetch-dest: empty' \
    -   -H 'sec-fetch-mode: cors' \
    -   -H 'sec-fetch-site: cross-site' \
    -   -H 'user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 
Safari/537.36' \
    -   --data-raw '{}'
```
- [x] Project level change requests aren't storing the user that created it, this is currently working for environment change requests
- [x] Fix email link from /projects/x/change-requests to project/x/change-requests
- [x] Manage project level change requests permission - The description should be clarified to be "Ability to create, delete and publish change requests associated with a project".

**Comment by zachaysan** [comment]
Regarding the the order of change requests seemingly random, I set them to paginate based on id not date descending since that is what most of the backend orders by for other endpoints. It should be functionally the same as created at.

**Comment by zachaysan** [comment]
> Approve is throwing a 500

This was solved by fixing the user being set on create. The bug was in the email method and a missing user blew the stack.

**Comment by zachaysan** [comment]
> In order to Store original rule ids so we can compare and diff change requests appropriately, as discussed let's call this field version_of to rules so we have a reference to the original rule that was potentially changed

This has been added in the following PRs:
 - https://github.com/Flagsmith/flagsmith-workflows/pull/63
 - https://github.com/Flagsmith/flagsmith-common/pull/11
 - https://github.com/Flagsmith/flagsmith/pull/4988
